### ISSUE TITLE
SDR: 80070057 (????????) -> Could not create compute shader "Sampling"

### ISSUE THREAD

**Issue by Skyline23** [crashfort/SourceDemoRender#10]
As the title

**Comment by crashfort** [comment]
Well for starters, is your GPU compatible?
Also, are the question marks part of the message?

**Comment by Skyline23** [comment]
My graphic card is NVIDIA GTX260. It seems that Its not compatible.

I dont know what you mean. But after I type startmovie abc.mp4, it will show this message.

**Comment by crashfort** [comment]
Quick research shows that the 260 only supports D3D10 not D3D11, sorry. As it is right now, the compute shaders are using CS5.0 which only exist in D3D11 and greater.

For the future, I will create an error message to say if its not compatible.

**Comment by Skyline23** [comment]
Thanks for your answer, I'm using the oldest one now.
