### ISSUE TITLE
Garrys mod fails to enable module "StartMovieCommand"

### ISSUE THREAD

**Issue by Zelec123** [crashfort/SourceDemoRender#11]
> PS D:\SDR> .\LauncherCLI.exe /GAME "D:\Steam\steamapps\common\GarrysMod\hl2.exe" /PATH "D:\Steam\steamapps\common\GarrysMod\garrysmod" "-novid -nojoy -windowed -w 1920 -h 1080"
SDR library version: 26
Appending parameters: "-steam -insecure +sv_lan 1 -console"
Searching game config for matching name
Found "Garry's Mod" in game config
Game: "Garry's Mod"
Executable: "D:\Steam\steamapps\common\GarrysMod\hl2.exe"
Directory: "D:\Steam\steamapps\common\GarrysMod\garrysmod"
Resource: "D:\SDR\"
Parameters: "-steam -insecure +sv_lan 1 -console"
Starting "Garry's Mod"
Injecting into "Garry's Mod"
Waiting for stage "Initialize"
Passed stage "Initialize"
Waiting for stage "Load"
SDR: Creating 23 game modules
SDR: Enabled module "MaterialsPtr"
SDR: Enabled module "EngineClientPtr"
SDR: Enabled module "View_Render"
SDR: Enabled module "StartMovie"
"StartMovieCommand"
{
    "GenericHookVariantInit"
    {
        "CreateHookBareShort"
        {
            "GetAddressFromJsonPattern"
            {
                "AddressFinder"
                {
                    Null pointer
                }
            }
        }
    }
}
SDR: Could not enable module "StartMovieCommand"
Could not pass stage "Load"
You can close this window now`

OS: Windows 10
GPU: Nvidia GTX-1050 TI (MSI 4GT OC)

Am I doing anything wrong on my end that prevents this from working?

**Comment by crashfort** [comment]
Thank you for the report, I fixed this in https://github.com/crashfort/SourceDemoRender/commit/56f4a485e7356834d255e7ded62b3480374f8e3a. All you have to do is update your configs by starting LauncherUI.

**Comment by Zelec123** [comment]
It works perfectly now. Thank you!

**Comment by Prikze** [comment]
I now have the exact same problem with gmod, I downloaded sdr just a few minutes ago, what should I do ?
