### ISSUE TITLE
Configuration support for Black Mesa (retail) request

### ISSUE THREAD

**Issue by Glitchvid** [crashfort/SourceDemoRender#12]
http://store.steampowered.com/app/362890/Black_Mesa/
Willing to provide a copy if you don't already own it.

**Comment by crashfort** [comment]
I do not own this game. To see if it's compatible, do you mind uploading its ``shaderapidx9.dll`` file inside the ``bin`` directory?

**Comment by Glitchvid** [comment]
This is from the public-beta branch of the game.
[shaderapidx9.zip](https://github.com/crashfort/SourceDemoRender/files/1588029/shaderapidx9.zip)

**Comment by crashfort** [comment]
Okay, it is compatible. I removed the link from your comment now. Will you supply with the game?

**Comment by Glitchvid** [comment]
Yeah, can only gift to friends on steam, just add me:
http://steamcommunity.com/id/glitchvid/

**Comment by crashfort** [comment]
Added in 28 among other things.
https://github.com/crashfort/SourceDemoRender/releases
