### ISSUE TITLE
Momentum in Game config seems to be outdated

### ISSUE THREAD

**Issue by Belastigen** [crashfort/SourceDemoRender#13]
I can't add Momentum as a game with SDR because it tells me it does not exist in game config.
I checked the game config, and it seems to list Momentum's exe as being in folder "Source SDK Base 2013 Multiplayer"
That's not the case with the current Steam version of Momentum, the exe is in folder "Momentum Mod"

What I assume to be the issue (I could be wrong), in GameConfig.json, here below

```
	"sourcemods\\momentum":
	{
		"Inherit": "Counter-Strike Source\\cstrike",
		"DisplayName": "Momentum",
		"ExecutableName": "Source SDK Base 2013 Multiplayer\\hl2.exe"
	},
```

**Comment by crashfort** [comment]
Steam Momentum is still in a private state until it reaches 1.0.0 so I will leave the current public version in there for now. You can edit the game config yourself if you want and then make it read only or something.

```
"Momentum Mod\\momentum":
{
	"Inherit": "Counter-Strike Source\\cstrike",
	"DisplayName": "Steam Momentum",
	"ExecutableName": "Momentum Mod\\hl2.exe"
}
```

**Comment by Belastigen** [comment]
It automatically changes the exe location back on launch of LauncherUI.exe, and doesn't seem to have any effect if I change it while the program is running. Should I be finding some other way to load SDR, rather than using LauncherUI?

**Comment by crashfort** [comment]
Okay, I added it now under a different name https://github.com/crashfort/SourceDemoRender/commit/02cd4417e175141a257b7bb7ab82bd379b924941.
