### ISSUE TITLE
Old Counter-Strike Source (1.0.0.34) support?

### ISSUE THREAD

**Issue by hypersad** [crashfort/SourceDemoRender#14]
Is there any support for old Counter-Strike Source?
```
Protocol version 7
Exe version 1.0.0.34 (cstrike)
Exe build: 17:27:58 Dec  3 2009 (4044)
```
It is also known as "v34".

I tried to launch it via SDR but got following error:
```
"MaterialsPtr"
{
    "GetAddressFromJsonPattern"
    {
        "AddressFinder"
        {
            Null pointer
        }
    }
}
SDR: Could not enable module "MaterialsPtr"
Could not pass stage "Load"
```

**Comment by crashfort** [comment]
I have no plans to support any version other than the latest.

**Comment by hypersad** [comment]
@crashfort that is sad.

Could you please explain and provide some documentation on how users can create and/or modify existing game configs? Like finding those patterns, etc.

**Comment by crashfort** [comment]
New entries can be added to the game config. Search for their names in the repository and you will find the code bound to them. The patterns you will find in a disassembler.

**Comment by hypersad** [comment]
@crashfort thanks, I hope I'll manage with it.

> The patterns you will find in a disassembler.

Is there any kind of guide for noobs about that? Also, could you provide disassembler name that you're using?

**Comment by crashfort** [comment]
You can use IDA.

**Comment by hypersad** [comment]
So... I've spent some time in IDA and didn't got anything. It is turned out too hard for me.

If you'll have free time (I'm not hurry), I hope you'll work on old CSS game config or work on examples about finding patterns and etc.

I've got answer and I'm closing this now.

**Comment by hypersad** [comment]
I've made some research and decided that it is unreal, because Source 7 is **too old** and didn't have some pointers and functions.

**Comment by tute123456** [comment]
Hi, this versión is the last update?
