### ISSUE TITLE
The sequence number 8 was not found in the DLL d2d1.dll.

### ISSUE THREAD

**Issue by hypersad** [crashfort/SourceDemoRender#15]
This error appears after "Looking for updates." step. If automatic updates is disables it doesn't appear at the startup, but still appears when I click on "Extensions" button. Unfortunately, I'm from Russia and have Russian language OS, so maybe I translated this error wrong, I'll include original error text.

```
Title 1: SDR Launcher UI: LauncherUI.exe - Порядковый номер не найден
Title 2: CiceroUIWndFrame: LauncherUI.exe - Порядковый номер не найден
Content: Порядковый номер 8 не найден в библиотеке DLL d2d1.dll.
```

Title could be one of two, but error is still the same.

OS: Windows 7 Ultimate SP1 x64

**Comment by crashfort** [comment]
The extension Direct2DContext uses D2D1 which minimum supported client is Windows 8 and Platform Update for Windows 7, [source](https://msdn.microsoft.com/en-us/library/windows/desktop/hh404273).

I have only tested on Windows 10 and I don't plan on carefully supporting older operating systems. Do you have the needed Windows 7 update if you really want to stay on that?

**Comment by hypersad** [comment]
> Do you have the needed Windows 7 update if you really want to stay on that?

Looks like I hadn't it. I've just installed it and all seems to work fine, thanks.
