### ISSUE TITLE
What do I do for directory?

### ISSUE THREAD

**Issue by xZempty** [crashfort/SourceDemoRender#16]
trying to get the game directory but it is saying " Game Half-Life 2 and Portal Source Unpack/hl2 does not exist in game config."

**Comment by xZempty** [comment]
I managed to get it working with the normal hl2 but nothing else. Plus I don't run on the steam version of hl2 so it's pointless. Now doing it it crashes loading up hl2 with SDR anyway.

**Comment by crashfort** [comment]
Steam versions are only supported. If your Steam version games are not installed in the correct locations you can edit the config files to duplicate a new entry with a different filter name.
