### ISSUE TITLE
Command to close the game when demo has ended

### ISSUE THREAD

**Issue by Traderain** [crashfort/SourceDemoRender#2]
It should do the same as the one that flashes the game's icon but this should close the game.

**Comment by JasonZ10** [comment]
When you put your endmovie command in the demo editor thing, just add "; quit" to the end

**Comment by crashfort** [comment]
Quit should not be used directly after endmovie as it may be done asynchronously and there are unprocessed frames. I had not had successful results using quit after all processing is done either.

**Comment by Traderain** [comment]
Maybe hook the destructor of the movie renderer and call it then?

**Comment by crashfort** [comment]
Added.
