### ISSUE TITLE
ConVar methods are deprecated. (At least in TF2)

### ISSUE THREAD

**Issue by mrsteyk** [crashfort/SourceDemoRender#21]
Game: TF2 (BuildID: 3001717)
Get/Set Bool/Float/Int are deprecated. Strings should be used. Proof:
![output](https://i.imgur.com/cdyCTY1.png)
![code](https://i.imgur.com/iAb8Rzn.png)

How i know that they are deprecated? They used to segfault me all the time i was writing a ConVar system for my cheats.

**Comment by crashfort** [comment]
done with svr
