### ISSUE TITLE
SDR refuses to render a video on my PC regardless of container

### ISSUE THREAD

**Issue by prestal99** [crashfort/SourceDemoRender#23]
Every time I try to record anything, it manages to successfully finish the recording process, but leaves me with an empty low MB (2mb per 4 seconds) container .avi with a black screen, and only game audio.
I have an AMD dual link GPU integrated HP Notebook laptop PC.
Specs:
https://i.imgur.com/PE93BJc.jpg
It just simply refuses to render any video, and I've been wanting to use this for over 2-3 months now but absolutely nothing seems to be working in any way, shape or form.
Note: I have a laptop with integrated APU, you mentioned something about this before, but I never fully figured out why it just simply refuses to work. I've managed to install Dokan for srcdemo2 on my pc successfully, with no real problems aside from the depreciation and it looking terrible

**Comment by crashfort** [comment]
SDR requires the high performance graphics adapter to be used in a hybrid setup. I can create a new release that forces it to be used, however I'm not sure how it will work in an APU setup.

**Comment by prestal99** [comment]
Unless there's some documentation out there on how to link SDR directly to use my APU setup (I can figure out a way to make that work somehow), that'd be fantastic, and I'll be looking forward to the next set of releases if this ever gets resolved.
