### ISSUE TITLE
SDR Don't Start

### ISSUE THREAD

**Issue by ryzim** [crashfort/SourceDemoRender#28]
Hello Guys,
I wanted to test out SDR in Gmod but im keep getting this error message when im launching it in the LauncherUI:

Parameters: "-steam -insecure +sv_lan 1 -console -window -w 1920 -h 1080"
Starting: "Garry's Mod"
Injecting into: "Garry's Mod"
Waiting for stage: "Initialize"
Process exited at stage "Initialize"
You can close this window now

Pls help

**Comment by crashfort** [comment]
done with svr
