### ISSUE TITLE
Failed to load plugin TF2

### ISSUE THREAD

**Issue by twisty-tf** [crashfort/SourceDemoRender#3]
Team Fortress 2, Windows 10

] exec sdr_load_mp
Loading unsigned module SourceDemoRender.Multiplayer.dll
Access to secure servers is disabled.
SDR: Creating 11 modules
SDR: Enabled module "OutputDebugString" -> kernel32.dll @ 0x75813570
SDR: Enabled module "ActivateMouse" -> engine.dll @ 0x69555730
SDR: Enabled module "AppActivate" -> engine.dll @ 0x6953FD10
SDR: Could not enable module "StartMovie" - "MH_ERROR_NOT_EXECUTABLE"
Failed to load plugin "SourceDemoRender.Multiplayer.dll"
Unable to load plugin "SourceDemoRender.Multiplayer.dll"

**Comment by crashfort** [comment]
I don't have TF2 installed right now but I can see straight away that those addresses are all out of bounds.

**Comment by twisty-tf** [comment]
Latest release of SourceDemoRender, whatever version that is sorry. No rush of course, thanks for the help!

**Comment by crashfort** [comment]
Thank you for the report, I have fixed this now, I'll provide a release soon.
