### ISSUE TITLE
CSGO support now that it's on D3D9ex

### ISSUE THREAD

**Issue by chrisfsampaio** [crashfort/SourceDemoRender#30]
Hey,
Great work here! I think this would be very handy on the CSGO community.
I see that you mentioned the reason for not supporting is because they were still on D3D9. Now that [they finally upgraded to D3D9ex](https://blog.counter-strike.net/index.php/2019/04/23870/), any chance we could have CSGO support as well? :)
Or maybe some pointers of what needs to be done. I'd be happy to contribute, just don't have enough experience to get it started myself.

**Comment by crashfort** [comment]
done with svr
