### ISSUE TITLE
Add support for other codecs?

### ISSUE THREAD

**Issue by Purple-CSGO** [crashfort/SourceDemoRender#34]
I've tried this software, and it works great in some cases.

But I found that it seems to only support x264 codec, yet codecs like h264_nvenc could improve the speed a lot faster. 

something like cqp=0 preset=hq pix_fmt=yuv444 or rgb, recording hugely faster to get footages and after all editing jobs are done

Then we could highly compress them to make very small archieves.

**Comment by crashfort** [comment]
Encoding takes part in a separate process and will not improve the performance of the game. Keyframe video is already supported through the ``video-x264-intra`` option.
