### ISSUE TITLE
Could not write data.

### ISSUE THREAD

**Issue by Nato390** [crashfort/SourceDemoRender#36]
I get the following error in the console every frame when recording

windows: Could not write 8294400 bytes to pipe 0x1ff0 (232)
Could not write 8294400 bytes to movie pipe. Has process 11752 ended?

Nothing appears in movies folder after recording, no matter the profile.
Simple fix?

**Comment by kallsyms** [comment]
You're probably missing an extension on the file name - use something like `startmovie t.mp4` not just `startmovie t`
