### ISSUE TITLE
Crashing on Tf2

### ISSUE THREAD

**Issue by Caatata** [crashfort/SourceDemoRender#5]
When the demo reaches the tick that I've set to start recording the game freezes and then crashes, I've tried deleting and reinstalling sdr and have tried a lot of different demos as well, any ideas whats causing this / how i can try and prevent it? thanks

**Comment by crashfort** [comment]
Show what the console says after loading.

**Comment by Caatata** [comment]
] exec sdr_load_mp
Loading unsigned module SourceDemoRender.Multiplayer.dll
Access to secure servers is disabled.
SDR: Creating 11 modules
SDR: Enabled module "OutputDebugString" -> kernel32.dll @ 0x74DB3570
SDR: Enabled module "ActivateMouse" -> engine.dll @ 0x614A57D0
SDR: Enabled module "AppActivate" -> engine.dll @ 0x6148FDB0
SDR: Enabled module "StartMovie" -> engine.dll @ 0x6134A7E0
SDR: Enabled module "StartMovieCommand" -> engine.dll @ 0x6134CCD0
SDR: Enabled module "EndMovie" -> engine.dll @ 0x61348B20
SDR: Enabled module "WriteMovieFrame" -> engine.dll @ 0x6148FBA0
SDR: Enabled module "SNDRecordBuffer" -> engine.dll @ 0x61309430
SDR: Enabled module "WaveCreateTmpFile" -> engine.dll @ 0x6131B5B0
SDR: Enabled module "WaveAppendTmpFile" -> engine.dll @ 0x6131B500
SDR: Enabled module "WaveFixupTmpFile" -> engine.dll @ 0x6131B740
SDR: Source Demo Render loaded
Loaded plugin "SourceDemoRender.Multiplayer.dll"

**Comment by crashfort** [comment]
Your version is outdated.

**Comment by Caatata** [comment]
the commands i put in the console before recording?

**Comment by crashfort** [comment]
Settings and demo.

**Comment by Caatata** [comment]
cl_interp 0
cl_drawhud 0
r_drawviewmodel 0
r_drawothermodels 0
sdr_render_samplespersecond 600
sdr_outputdir [folder name]

i tried to attach the demo but it said it doesnt support that file type, the demo seems fine tho

**Comment by crashfort** [comment]
I need the demo.

**Comment by Caatata** [comment]
Sorry I've been away for a couple says so haven't been able to reply, any demo from stv.resurfed.com will work, I've tried loads of different ones and i always get the same crashing when i get to the startmovie tick

**Comment by crashfort** [comment]
I see what happens now. TF2 does things differently and I'm not sure if it can be fixed. I'll see.

**Comment by crashfort** [comment]
Okay, I managed to fix it. I'll provide a release soon.
