### ISSUE TITLE
Make optionally disable auto-stop for capturing multiple demos

### ISSUE THREAD

**Issue by SmileyAG** [crashfort/SourceDemoRender#54]
Useful for recording a demo-sequence via `startdemos` or some external tools which does like that: https://github.com/thisis2838/startdemos-plus

To do that, needs to implement a custom parameter (like `-notstop`), and adds a !check for that in this line:

https://github.com/crashfort/SourceDemoRender/blob/8fbfcd4fb2280fb11bf65fe732a568bd18599855/src/game_standalone.cpp#L715

**Comment by crashfort** [comment]
Done in SVR 37.
