### ISSUE TITLE
CS:GO overlay

### ISSUE THREAD

**Issue by tslashd** [crashfort/SourceDemoRender#55]
Overlay for CS:GO is showing up, but value always stays 0

Tested with multiple demos, still works fine with [version ](https://github.com/crashfort/SourceDemoRender/pull/43#issuecomment-883022079)from #43 comments

**Comment by dPexxIAM** [comment]
Issue persists with the latest release https://github.com/crashfort/SourceDemoRender/releases/tag/37

**Comment by rtldg** [comment]
https://github.com/crashfort/SourceDemoRender/pull/57 should:tm: fix this

**Comment by crashfort** [comment]
Done in SVR 38.
