### ISSUE TITLE
Current Versions do not work since CSGO's update

### ISSUE THREAD

**Issue by ImDini** [crashfort/SourceDemoRender#56]
Since the latest CSGO update SDR/SVR no longer launches sadly

![image](https://user-images.githubusercontent.com/16860411/145729666-590a9cc8-4263-4add-9d67-8741c819e279.png)

**Comment by crashfort** [comment]
This is an old version of SVR that is not supported.

**Comment by ImDini** [comment]
Above screenshot was from your release before the most recent update
