### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by Slips-PC** [crashfort/SourceDemoRender#62]
Any chance of a version for Linux systems any time soon? This software looks interesting and I'd love to try it out but I don't use Windows.

**Comment by crashfort** [comment]
A Linux version will not happen. A Linux version would double all reverse engineering work and need a separate graphics system, along with coming up with workarounds of a lacking Linux API in some places. Things would not work fast with OpenGL with the special use that SVR needs (same restriction that SVR requires D3D9Ex, and will not work with D3D9 - OpenGL is like D3D9 in that regard).

**Comment by maxpain** [comment]
@YaLTeR did fantastic work on optimizing the encoding pipeline for Half-Life, especially converting colors in GPU and using Vulkan to capture frames. Maybe we can do something like this for Source?

**Comment by Ristovski** [comment]
@crashfort What exactly is this limitation you mentioned, that requires the usage of D3D9Ex?
