### ISSUE TITLE
Recording Times

### ISSUE THREAD

**Issue by BernardKelly** [crashfort/SourceDemoRender#7]
I want to record my 2 hour speed runs and surf demos... whats the best options to lower record time? It takes up 2gb and 30+ min for 3minutes... any alternatives or settings that I can change ?

 Awesome tool btw

**Comment by crashfort** [comment]
Do not use image sequence. It's the slowest possible method of recording and it will be removed in the next update in favor of RGB video. The next update will also provide GPU acceleration which might help your case significantly.

**Comment by BernardKelly** [comment]
Alright well I use x264 but hopefully the GPU acceleration helps. Thank you
