### ISSUE TITLE
CS:S crash on launch

### ISSUE THREAD

**Issue by Belastigen** [crashfort/SourceDemoRender#8]
> F:\Program Files\Steam\SteamApps\common\Counter-Strike Source\cstrike\SDR>.\LauncherCLI.exe "F:\Program Files\Steam\SteamApps\common\Counter-Strike Source\hl2.exe" -window -w 1920 -h 1080 -novid
> Searching game config for matching name
> Found "cstrike" in game config
> Appending parameters: "-steam -insecure +sv_lan 1 -console"
> Game: "cstrike"
> Executable path: "F:\Program Files\Steam\SteamApps\common\Counter-Strike Source\hl2.exe"
> Directory: "F:\Program Files\Steam\SteamApps\common\Counter-Strike Source\cstrike\"
> Parameters: "-steam -insecure +sv_lan 1 -console -window -w 1920 -h 1080 -novid"
> Starting "cstrike"
> Injecting into "cstrike"
> Waiting for signals
> Received remote SDR signal
> SDR initialized in "cstrike"
> Waiting for finished loading event
> SDR fully loaded
> SDR: Creating 26 modules
> SDR: Enabled module "ActivateMouse"
> SDR: Enabled module "AppActivate"
> SDR: Enabled module "MaterialsPtr"
> SDR: Enabled module "MaterialSystem_GetBackBufferDimensions"
> SDR: Enabled module "EngineClientPtr"
> SDR: Enabled module "EngineClient_ConsoleVisible"
> SDR: Enabled module "EngineClient_FlashWindow"
> SDR: Enabled module "EngineClient_ClientCommand"
> SDR: Enabled module "D3D9_Device"
> SDR: Enabled module "DrawLoading"
> SDR: Enabled module "View_Render"
> SDR: Enabled module "StartMovie"
> SDR: Enabled module "StartMovieCommand"
> SDR: Enabled module "EndMovie"
> SDR: Enabled module "EndMovieCommand"
> SDR: Enabled module "SUpdateGuts"
> SDR: Enabled module "CvarPtr"
> SDR: Enabled module "Cvar_FindVar"
> SDR: Enabled module "ConVar_Info"
> SDR: Enabled module "ConVar_Constructor3"
> SDR: Enabled module "ConCommandBase_Info"
> SDR: Enabled module "CCommand_Info"
> SDR: Enabled module "ConCommand_Info"
> SDR: Enabled module "ConCommand_Constructor1"
> SDR: Enabled module "Console_Info"
> SDR: Enabled module "Engine_Info"
> SDR: Startup procedure (1/2): "MovieRecord console variables"
> SDR: Startup procedure (2/2): "PluginInterface console commands"
> SDR: Library version: 20
> SDR: Current game: "cstrike"
> SDR: Source Demo Render loaded
> You can close this window now

Haven't found a clear guide on using recent versions of SDR, so I easily could have just done some setup wrong, or somesuch. I used to use it in version 6 or so, but it's not the same anymore.

Running the batch file, the prompt prints what I've pasted above, and then game launches and I get the Windows error that it has stopped responding. (Different error to 'is not responding', as that one you can just wait out, usually.)

**Comment by crashfort** [comment]
Post your OS.

**Comment by Belastigen** [comment]
Windows 10

**Comment by crashfort** [comment]
Sorry, I cannot reproduce. I will need more details what you are doing.

**Comment by crashfort** [comment]
A difference I notice in your log is that your ``Directory`` doesn't have a trailing backslash which it should have, can you try downloading the latest version again? https://github.com/crashfort/SourceDemoRender/releases

**Comment by Belastigen** [comment]
Okay, well, interestingly enough, redownloading it actually worked this time... I guess that's how it goes when you finally ask for help lol, problem just kinda fixes through the most obvious solution you've tried a hundred times.

I'm now launching the game fine, however when I try to "startmovie [name]" it gives me this error:

> ] startmovie testmovie
> SDR: Could not allocate output context for "F:\Program Files\Steam\SteamApps\common\Counter-Strike Source\movies\testmovie"

Tried with all sorts of different output directories.
Should I be creating a new ticket for that, or is it something blatant that I've missed?

**Comment by crashfort** [comment]
You need to have a file extension, the available ones are written in the [readme](https://github.com/crashfort/SourceDemoRender#instructions).
