### ISSUE TITLE
take a look at csgo support again?

### ISSUE THREAD

**Issue by formatme** [crashfort/SourceDemoRender#9]
can you take a look at csgo support again?

**Comment by crashfort** [comment]
The statement in the [readme](https://github.com/crashfort/SourceDemoRender#is-my-game-supported) is still accurate. The technology currently used in CSGO is too outdated so it can't be supported.

**Comment by formatme** [comment]
any hacks around it?

**Comment by crashfort** [comment]
Don't think so, unfortunately.
